In [ ]:
!pip install pythainlp

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting pythainlp
  Downloading pythainlp-3.1.1-py3-none-any.whl (9.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.6/9.6 MB 90.1 MB/s eta 0:00:00
Requirement already satisfied: requests>=2.22.0 in /usr/local/lib/python3.9/dist-packages (from pythainlp) (2.25.1)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/local/lib/python3.9/dist-packages (from requests>=2.22.0->pythainlp) (4.0.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.9/dist-packages (from requests>=2.22.0->pythainlp) (2022.12.7)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.9/dist-packages (from requests>=2.22.0->pythainlp) (1.26.14)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.9/dist-packages (from requests>=2.22.0->pythainlp) (2.10)
Installing collected packages: pythainlp
Successfully installed pythainlp-3.1.1

In [ ]:
import pandas as pd
import numpy as np
from pythainlp import word_tokenize

In [ ]:
# from google.colab import drive
# drive.mount('/content/drive')

## Load Data

In [ ]:
!gdown 1sku3URDmtR77SK355ciPjW19sP7dO8Q-

Downloading...
From: https://drive.google.com/uc?id=1sku3URDmtR77SK355ciPjW19sP7dO8Q-
To: /content/ss3-nlp-cmsk-chatbot.zip
100% 130k/130k [00:00<00:00, 79.4MB/s]

In [ ]:
!unzip '/content/ss3-nlp-cmsk-chatbot.zip'

Archive:  /content/ss3-nlp-cmsk-chatbot.zip
  inflating: context/1345136.txt
  inflating: context/1345138.txt
  inflating: context/1345140.txt
  inflating: context/1345141.txt
  inflating: context/1345142.txt
  inflating: context/1345143.txt
  inflating: context/1345144.txt
  inflating: context/1345146.txt
  inflating: context/1345148.txt
  inflating: context/1345149.txt
  inflating: context/1345150.txt
  inflating: context/1345154.txt
  inflating: context/1345156.txt
  inflating: context/1345157.txt
  inflating: context/1345158.txt
  inflating: context/1345160.txt
  inflating: context/1345161.txt
  inflating: context/1345169.txt
  inflating: context/1345171.txt
  inflating: context/1345172.txt
  inflating: context/1345173.txt
  inflating: context/1345175.txt
  inflating: context/1345177.txt
  inflating: context/1345178.txt
  inflating: context/1345179.txt
  inflating: context/1345181.txt
  inflating: context/1345183.txt
  inflating: context/1345184.txt
  inflating: context/1345185.txt
  inflating: context/1345186.txt
  inflating: context/1345187.txt
  inflating: context/1345188.txt
  inflating: context/1345191.txt
  inflating: context/1345192.txt
  inflating: context/1345193.txt
  inflating: context/1345194.txt
  inflating: context/1345195.txt
  inflating: context/1345196.txt
  inflating: context/1345197.txt
  inflating: context/1345199.txt
  inflating: context/1345200.txt
  inflating: context/1345201.txt
  inflating: sample_submission.csv
  inflating: small_test.csv
  inflating: train.csv

In [ ]:
qa = pd.read_csv('/content/train.csv')

In [ ]:
qa_df = qa.iloc[:,1:3]
qa_df

,question,answer
0,ใครเป็นผู้ออกตราสารหนี้ภาคเอกชน ไร้ใบตราสาร,ไม่มีการรวมศูนย์อย่างตราสารภาครัฐ แต่ส่วนใหญ่ด...
1,Penny Stock หุ้นเหรียญ มีลักษณะอย่างไร,*\tหุ้นที่มีราคาซื้อขายต่อหน่วยต่ำ (ในสหรัฐฯ ค...
2,ราคาต้นงวดคืออะไร,ราคาต้นทุนหรือราคาซื้อ
3,อัตราการใช้สิทธิของ NVDR คือเท่าไหร่,1 : 1 (NVRD : สินทรัพย์อ้างอิง) เสมอ
4,หนังสือชี้ชวนส่วนสรุปข้อมูลสำคัญ (Fund Fact Sh...,เอกสารที่ให้ข้อมูลที่สำคัญกับผู้ลงทุน
...,...,...
405,กองทุนรวมตราสารหนี้ระยะยาว (Long-Term Fixed-In...,ลงทุนในตราสารหนี้ที่มีอายุเฉลี่ยของตราสารหนี้ถ...
406,อัตราดอกเบี้ยนโยบายเปลี่ยนแปลง จะส่งผลอย่างไร,"อัตราดอกเบี้ยต่างๆในตลาดไม่ว่าจะเป็น เงินฝาก, ..."
407,การลงทุนที่เน้นลงทุนในหุ้นที่มีแนวโน้มการเติบโ...,การลงทุนแบบเน้นการเติบโต (Growth Investing)
408,กองทุนที่ได้สิทธิประโยชน์ทางภาษี คืออะไร,กองทุนรวมที่ให้สิทธิประโยชน์ทางภาษีกับผู้ลงทุน...
409,บัญชีเงินสดปกติ (Normal Cash) คืออะไร,บัญชีที่จะเก็บเงินค่าซื้อหลักทรัพย์เป็นเงินสดเ...

In [ ]:
# label
qa_df['label'] = 'qa_mode'
qa_df

,question,answer,label
0,ใครเป็นผู้ออกตราสารหนี้ภาคเอกชน ไร้ใบตราสาร,ไม่มีการรวมศูนย์อย่างตราสารภาครัฐ แต่ส่วนใหญ่ด...,qa_mode
1,Penny Stock หุ้นเหรียญ มีลักษณะอย่างไร,*\tหุ้นที่มีราคาซื้อขายต่อหน่วยต่ำ (ในสหรัฐฯ ค...,qa_mode
2,ราคาต้นงวดคืออะไร,ราคาต้นทุนหรือราคาซื้อ,qa_mode
3,อัตราการใช้สิทธิของ NVDR คือเท่าไหร่,1 : 1 (NVRD : สินทรัพย์อ้างอิง) เสมอ,qa_mode
4,หนังสือชี้ชวนส่วนสรุปข้อมูลสำคัญ (Fund Fact Sh...,เอกสารที่ให้ข้อมูลที่สำคัญกับผู้ลงทุน,qa_mode
...,...,...,...
405,กองทุนรวมตราสารหนี้ระยะยาว (Long-Term Fixed-In...,ลงทุนในตราสารหนี้ที่มีอายุเฉลี่ยของตราสารหนี้ถ...,qa_mode
406,อัตราดอกเบี้ยนโยบายเปลี่ยนแปลง จะส่งผลอย่างไร,"อัตราดอกเบี้ยต่างๆในตลาดไม่ว่าจะเป็น เงินฝาก, ...",qa_mode
407,การลงทุนที่เน้นลงทุนในหุ้นที่มีแนวโน้มการเติบโ...,การลงทุนแบบเน้นการเติบโต (Growth Investing),qa_mode
408,กองทุนที่ได้สิทธิประโยชน์ทางภาษี คืออะไร,กองทุนรวมที่ให้สิทธิประโยชน์ทางภาษีกับผู้ลงทุน...,qa_mode
409,บัญชีเงินสดปกติ (Normal Cash) คืออะไร,บัญชีที่จะเก็บเงินค่าซื้อหลักทรัพย์เป็นเงินสดเ...,qa_mode

In [ ]:
!gdown 1tojjXtJng_8lWGEUjCENVZ2ofjb4xe-h
chat_df = pd.read_csv('/content/chitchat_train_data - Sheet1.csv')
chat_df

Downloading...
From: https://drive.google.com/uc?id=1tojjXtJng_8lWGEUjCENVZ2ofjb4xe-h
To: /content/chitchat_train_data - Sheet1.csv
100% 29.3k/29.3k [00:00<00:00, 37.6MB/s]

,Q,A
0,วันนี้ฝนจะตกมั้ยเนี่ย,ไม่แน่ใจเหมือนกัน ยังไม่ได้ดูพยากรณ์อากาศ
1,ต้องจบอะไรมาก่อนถึงจะเรียนได้,จบอะไรมาก็เรียนได้จ้า สู้ไปด้วยกันนะ
2,ยากจังเลย เรียนไม่รู้เรื่องทำยังไงดี,เป็นแบบนี้ทุกคนแหละ มันต้องใช้เวลา
3,ทำยังไงถึงเรียนเก่ง,ลองทบทวนเนื้อหาบ่อย ๆ และลองทำโจทย์เยอะ ๆ นะ
4,อยากรวยทำยังไงดี,อยากรวยเหมือนกัน รู้แล้วมาบอกกันด้วยนะ
...,...,...
129,คุณชอบเบียร์ประเภทไหน,ฉันไม่ดื่มเบียร์ แต่ฉันชอบมาการิต้าที่ดี
130,ของหวานประเภทไหนที่คุณชอบ,ฉันชอบทุกอย่างที่มีช็อคโกแลต เค้กช็อคโกแลต ไอศ...
131,คุณมีเนื้อเพลงที่ชอบไหม,"ฉันเชื่อว่าฉันบินได้"" - อาร์. เคลลี่"
132,ชาชนิดไหนที่คุณชอบ,ฉันชอบชาเขียว ให้ความสดชื่นและสุขภาพดี
133,คุณชอบออกกำลังกายประเภทไหน,ฉันชอบเล่นโยคะ

In [ ]:
chat_df.rename(columns={'Q':'question','A':'answer'}, inplace=True)

In [ ]:
chat_df['label'] = 'chat_mode'
chat_df

,question,answer,label
0,วันนี้ฝนจะตกมั้ยเนี่ย,ไม่แน่ใจเหมือนกัน ยังไม่ได้ดูพยากรณ์อากาศ,chat_mode
1,ต้องจบอะไรมาก่อนถึงจะเรียนได้,จบอะไรมาก็เรียนได้จ้า สู้ไปด้วยกันนะ,chat_mode
2,ยากจังเลย เรียนไม่รู้เรื่องทำยังไงดี,เป็นแบบนี้ทุกคนแหละ มันต้องใช้เวลา,chat_mode
3,ทำยังไงถึงเรียนเก่ง,ลองทบทวนเนื้อหาบ่อย ๆ และลองทำโจทย์เยอะ ๆ นะ,chat_mode
4,อยากรวยทำยังไงดี,อยากรวยเหมือนกัน รู้แล้วมาบอกกันด้วยนะ,chat_mode
...,...,...,...
129,คุณชอบเบียร์ประเภทไหน,ฉันไม่ดื่มเบียร์ แต่ฉันชอบมาการิต้าที่ดี,chat_mode
130,ของหวานประเภทไหนที่คุณชอบ,ฉันชอบทุกอย่างที่มีช็อคโกแลต เค้กช็อคโกแลต ไอศ...,chat_mode
131,คุณมีเนื้อเพลงที่ชอบไหม,"ฉันเชื่อว่าฉันบินได้"" - อาร์. เคลลี่",chat_mode
132,ชาชนิดไหนที่คุณชอบ,ฉันชอบชาเขียว ให้ความสดชื่นและสุขภาพดี,chat_mode
133,คุณชอบออกกำลังกายประเภทไหน,ฉันชอบเล่นโยคะ,chat_mode

In [ ]:
df = pd.concat([qa_df,chat_df], axis=0)
df

,question,answer,label
0,ใครเป็นผู้ออกตราสารหนี้ภาคเอกชน ไร้ใบตราสาร,ไม่มีการรวมศูนย์อย่างตราสารภาครัฐ แต่ส่วนใหญ่ด...,qa_mode
1,Penny Stock หุ้นเหรียญ มีลักษณะอย่างไร,*\tหุ้นที่มีราคาซื้อขายต่อหน่วยต่ำ (ในสหรัฐฯ ค...,qa_mode
2,ราคาต้นงวดคืออะไร,ราคาต้นทุนหรือราคาซื้อ,qa_mode
3,อัตราการใช้สิทธิของ NVDR คือเท่าไหร่,1 : 1 (NVRD : สินทรัพย์อ้างอิง) เสมอ,qa_mode
4,หนังสือชี้ชวนส่วนสรุปข้อมูลสำคัญ (Fund Fact Sh...,เอกสารที่ให้ข้อมูลที่สำคัญกับผู้ลงทุน,qa_mode
...,...,...,...
129,คุณชอบเบียร์ประเภทไหน,ฉันไม่ดื่มเบียร์ แต่ฉันชอบมาการิต้าที่ดี,chat_mode
130,ของหวานประเภทไหนที่คุณชอบ,ฉันชอบทุกอย่างที่มีช็อคโกแลต เค้กช็อคโกแลต ไอศ...,chat_mode
131,คุณมีเนื้อเพลงที่ชอบไหม,"ฉันเชื่อว่าฉันบินได้"" - อาร์. เคลลี่",chat_mode
132,ชาชนิดไหนที่คุณชอบ,ฉันชอบชาเขียว ให้ความสดชื่นและสุขภาพดี,chat_mode
133,คุณชอบออกกำลังกายประเภทไหน,ฉันชอบเล่นโยคะ,chat_mode

## **Logistic Regression + CVEC + BOW**

In [ ]:
def text_process(text):

    # Word Tokenize
    final = word_tokenize(text)

    # # Split word with Space
    final = " ".join(word for word in final)

    return final

In [ ]:
df['text_token'] = df['question'].apply(text_process)
df

,question,answer,label,text_token
0,ใครเป็นผู้ออกตราสารหนี้ภาคเอกชน ไร้ใบตราสาร,ไม่มีการรวมศูนย์อย่างตราสารภาครัฐ แต่ส่วนใหญ่ด...,qa_mode,ใคร เป็น ผู้ ออก ตราสาร หนี้ ภาคเอกชน ไร้ ใบ...
1,Penny Stock หุ้นเหรียญ มีลักษณะอย่างไร,*\tหุ้นที่มีราคาซื้อขายต่อหน่วยต่ำ (ในสหรัฐฯ ค...,qa_mode,Penny Stock หุ้น เหรียญ มี ลักษณะ อย่างไร
2,ราคาต้นงวดคืออะไร,ราคาต้นทุนหรือราคาซื้อ,qa_mode,ราคา ต้น งวด คือ อะไร
3,อัตราการใช้สิทธิของ NVDR คือเท่าไหร่,1 : 1 (NVRD : สินทรัพย์อ้างอิง) เสมอ,qa_mode,อัตรา การ ใช้ สิทธิ ของ NVDR คือ เท่าไหร่
4,หนังสือชี้ชวนส่วนสรุปข้อมูลสำคัญ (Fund Fact Sh...,เอกสารที่ให้ข้อมูลที่สำคัญกับผู้ลงทุน,qa_mode,หนังสือชี้ชวน ส่วน สรุป ข้อมูล สำคัญ ( Fund ...
...,...,...,...,...
129,คุณชอบเบียร์ประเภทไหน,ฉันไม่ดื่มเบียร์ แต่ฉันชอบมาการิต้าที่ดี,chat_mode,คุณ ชอบ เบียร์ ประเภท ไหน
130,ของหวานประเภทไหนที่คุณชอบ,ฉันชอบทุกอย่างที่มีช็อคโกแลต เค้กช็อคโกแลต ไอศ...,chat_mode,ของหวาน ประเภท ไหน ที่ คุณ ชอบ
131,คุณมีเนื้อเพลงที่ชอบไหม,"ฉันเชื่อว่าฉันบินได้"" - อาร์. เคลลี่",chat_mode,คุณ มี เนื้อเพลง ที่ ชอบ ไหม
132,ชาชนิดไหนที่คุณชอบ,ฉันชอบชาเขียว ให้ความสดชื่นและสุขภาพดี,chat_mode,ชา ชนิด ไหน ที่ คุณ ชอบ
133,คุณชอบออกกำลังกายประเภทไหน,ฉันชอบเล่นโยคะ,chat_mode,คุณ ชอบ ออกกำลังกาย ประเภท ไหน

In [ ]:
df['text_token'][0]

0    [ใคร, เป็น, ผู้, ออก, ตราสาร, หนี้, ภาคเอกชน, ...
0                    [วันนี้, ฝน, จะ, ตก, มั้ย, เนี่ย]
Name: text_token, dtype: object

In [ ]:
# Split Train and Test
from sklearn.model_selection import train_test_split

In [ ]:
X = df[['text_token']]
y = df['label']

X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size=0.2,
                                                    random_state=25)

In [ ]:
# Use Count Vectorizer
from sklearn.feature_extraction.text import CountVectorizer

cvec = CountVectorizer(analyzer=lambda x:x.split(' '))
cvec.fit_transform(X_train['text_token'])

cvec.vocabulary_

{'ทำไม': 410,
 'จึง': 324,
 'ต้อง': 389,
 'ติดตาม': 377,
 'ภาวะ': 517,
 'การซื้อขาย': 221,
 'กระบวนการ': 202,
 'ตรวจสอบ': 358,
 'การ': 216,
 'เปิดบัญชี': 743,
 'หลักทรัพย์': 656,
 'มี': 529,
 'วิธี': 589,
 'ใด': 817,
 'บ้าง': 460,
 'พันธบัตร': 507,
 'ชดเชย': 329,
 'เงินเฟ้อ': 718,
 '': 0,
 '(': 3,
 'Inflation-Linked': 77,
 'bond': 183,
 ')': 4,
 'คือ': 290,
 'อะไร': 683,
 'Free': 64,
 'hold': 186,
 'เบื่อ': 740,
 'อ่ะ': 695,
 'ซื้อ': 345,
 'ตราสาร': 360,
 'หนี้': 643,
 'เมื่อใด': 758,
 'กองทุนรวม': 213,
 'ที่': 413,
 'ไม่': 834,
 'ความเสี่ยง': 283,
 'ต่างประเทศ': 385,
 'Warrant': 167,
 'ไทย': 830,
 'ภาษี': 518,
 'เมื่อ': 757,
 'ส่งมอบ': 635,
 'หรือไม่': 654,
 'แบ่ง': 790,
 'ตาม': 372,
 'ผู้': 489,
 'ออก': 680,
 'หนังสือ': 641,
 'เล่ม': 772,
 'โปรด': 809,
 'ของ': 245,
 'คุณ': 292,
 'บทลงโทษ': 444,
 'ความผิด': 277,
 'ข้อบังคับ': 256,
 'ตลาดหลักทรัพย์': 362,
 'Limit': 88,
 'Price': 124,
 'Order': 114,
 'วันหยุด': 587,
 'ดี': 350,
 'ที่สุด': 418,
 'เคย': 708,
 'ไป': 831,
 'ผู้ค้า': 490,
 'สร้าง': 607,
 'รายได้': 563,
 'จาก': 322,
 'ที่ใด': 420,
 'วัน': 585,
 'ครบกำหนด': 265,
 'ไถ่ถอน': 829,
 'Maturity': 96,
 'Date': 43,
 'ง่วง': 307,
 'ETF': 46,
 'Exchange': 53,
 'Trade': 160,
 'Fund': 65,
 'NVRD': 107,
 'อ้างอิง': 698,
 'กับ': 215,
 'ประเภท': 469,
 'ได้': 826,
 'การลงทุน': 227,
 'แบบ': 789,
 'เน้น': 738,
 'คุณค่า': 293,
 'Value': 165,
 'Investing': 82,
 'วิธีการ': 590,
 'อย่างไร': 676,
 'Asset': 24,
 'Based': 26,
 'Approach': 23,
 'NC': 103,
 'จะ': 310,
 'มองโลกในแง่ดี': 522,
 'เผชิญ': 748,
 'ความ': 270,
 'ท้าทาย': 426,
 'ยังไง': 539,
 'ของขวัญ': 246,
 'ให้': 824,
 'แฟน': 793,
 'นายหน้า': 438,
 'ค้า': 299,
 'ส่วน': 636,
 'ได้มา': 827,
 'ใน': 818,
 'ครั้งแรก': 267,
 'ลงทุน': 572,
 'การกำกับ': 217,
 'ดูแล': 351,
 'ส่งผล': 634,
 'ต่อ': 382,
 'บริษัท': 446,
 'สมาชิก': 604,
 'บล.': 450,
 'บทวิเคราะห์': 445,
 'เชิง': 722,
 'ลึก': 579,
 'ควร': 269,
 'องค์ประกอบ': 672,
 'เพิ่มเติม': 753,
 'กิน': 236,
 'การประเมิน': 224,
 'มูลค่า': 537,
 'จ่าย': 327,
 'ดอกเบี้ย': 347,
 'ทำ': 405,
 'รูปแบบ': 567,
 'กระแส': 203,
 'เงินสด': 717,
 'ชอบ': 332,
 'เริ่มต้น': 762,
 'ใหม่': 823,
 'ด้วย': 352,
 'ไหน': 839,
 'อัตรา': 684,
 'ใช้': 816,
 'สิทธิ': 622,
 'NVDR': 106,
 'เท่าไหร่': 732,
 'ประโยชน์': 470,
 'ด้าน': 353,
 'ตลาด': 361,
 'การเงิน': 230,
 'รัฐวิสาหกิจ': 554,
 'ผู้ใด': 499,
 'กองทุน': 212,
 'General': 67,
 'Fixed': 60,
 'Income': 75,
 'Securitization': 145,
 'XW': 175,
 'กลุ่ม': 210,
 'TBX': 156,
 'Cash': 32,
 'Flow': 63,
 'รักษา': 553,
 'สมดุล': 600,
 'ระหว่าง': 550,
 'การทำงาน': 222,
 'และ': 797,
 'ชีวิต': 337,
 'แล้ว': 798,
 'มีความสุข': 530,
 '\r': 2,
 'เมื่อไม่นานมานี้': 759,
 'ไปเที่ยว': 833,
 'ที่ไหน': 421,
 'กัน': 214,
 'ผิดนัด': 488,
 'ชำระหนี้': 336,
 'Credit': 39,
 'risk': 191,
 'เอ': 782,
 'ไอ': 842,
 'ฉัน': 328,
 'จดจ่อ': 308,
 'อยู่': 674,
 'การเรียน': 231,
 '?': 15,
 'Combined': 34,
 'Method': 97,
 'ผสม': 487,
 'XN': 173,
 'ใส่': 821,
 'ชุด': 341,
 'สัมภาษณ์': 613,
 'งาน': 303,
 'ลูกอม': 581,
 'ชนิด': 330,
 'เปิด': 742,
 'เลิก': 767,
 'โครงการ': 804,
 'ราคา': 558,
 'หุ้นสามัญ': 666,
 'ลดลง': 574,
 'รุนแรง': 566,
 'เนื่องจาก': 736,
 'ที่จะ': 414,
 'ล้มละลาย': 582,
 'หุ้นกู้': 664,
 'แปลง': 791,
 'สภาพ': 597,
 'ใบ': 820,
 'Scrip': 141,
 'ลักษณะ': 576,
 'อัตราดอกเบี้ย': 685,
 'นโยบาย': 442,
 'พรบ.': 503,
 'อาหารเช้า': 691,
 'เพื่อ': 754,
 'สุขภาพ': 629,
 'เธอ': 734,
 'ไม่ค่อย': 835,
 'เข้าใจ': 707,
 'เรา': 761,
 'NP': 104,
 'ของหวาน': 247,
 'อยาก': 673,
 'ตื่น': 381,
 'เลย': 766,
 'ตัวอย่าง': 367,
 'ข้อมูล': 257,
 'สถิติ': 594,
 'สำคัญ': 619,
 'ถูก': 394,
 'วิเคราะห์': 591,
 'LTF': 86,
 'ปันผล': 479,
 'โย่ว!!': 812,
 'ปัจจัย': 475,
 'มหภาค': 520,
 'Macro': 93,
 'Factor': 57,
 'ชำระ': 335,
 'Net': 109,
 'Clearing': 33,
 'ปลาย': 474,
 'งวด': 302,
 'บริษัทจำกัด': 447,
 'กรณี': 198,
 'เข้ามา': 706,
 'เพิ่มขึ้น': 752,
 'ผู้เกี่ยวข้อง': 497,
 'กี่': 237,
 'ผู้ลงทุน': 495,
 'สามารถ': 617,
 'ตัดสินใจ': 365,
 'ถือ': 392,
 '/': 5,
 'เฉย': 721,
 'ๆ': 844,
 'ลด': 573,
 'ความเครียด': 280,
 'NAV': 102,
 'แสดงให้เห็น': 799,
 'ขยัน': 243,
 'ขึ้น': 252,
 'นะ': 433,
 'เกณฑ์': 700,
 'หยุด': 652,
 'ชั่วคราว': 333,
 'ยาว': 541,
 'Buy': 30,
 'and': 180,
 'Hold': 72,
 'Strategy': 152,
 'สูตร': 632,
 'การคำนวณ': 218,
 'เงินปันผล': 716,
 'สมาคม': 603,
 'หน้าที่': 649,
 'MLR': 92,
 'Minimum': 100,
 'Load': 90,
 'Rate': 131,
 'ราย': 559,
 'งานการ': 304,
 'ถือครอง': 393,
 'สินทรัพย์': 627,
 'เป็น': 744,
 'รายใหญ่': 562,
 'ดัชนี': 349,
 'Index': 76,
 'พัก': 505,
 'ก็ได้': 239,
 'มึน': 535,
 'บ่อย': 457,
 'รับซื้อ': 556,
 'เหลือ': 781,
 'ขายต่อ': 250,
 'หลักการ': 655,
 'ปิด': 481,
 '16.30': 10,
 '–': 846,
 '16.40': 11,
 'น.': 430,
 'รายละเอียด': 561,
 'Market': 95,
 'timing': 192,
 'จับ': 320,
 'จังหวะ': 312,
 '14.00': 8,
 '14.30': 9,
 'สนุก': 595,
 'มาตรการ': 526,
 'การป้องกัน': 225,
 'เกิด': 701,
 'เป็นธรรม': 745,
 'ที่มา': 416,
 'วัตถุประสงค์': 584,
 'มหาชน': 521,
 'เพราะอะไร': 749,
 'ถึง': 391,
 'เรียนหนังสือ': 765,
 'เครื่องมือ': 710,
 'ทดแทน': 395,
 'อสังหาริมทรัพย์': 678,
 'จัดตั้ง': 315,
 'เพิ่ม': 751,
 'ทุน': 423,
 'อีก': 693,
 'การรักษา': 226,
 'แรงจูงใจ': 796,
 'ใคร': 815,
 'ภาคเอกชน': 516,
 'TRIS': 157,
 'Rating': 132,
 'ก.ล.ต.': 196,
 'ปัจจัยสำคัญ': 476,
 'มีผลต่อ': 533,
 'หุ้น': 663,
 'ทางเลือก': 404,
 'Alternative': 21,
 'Investment': 83,
 'SETSMART': 138,
 'Enterprise': 49,
 'Mid-cap': 99,
 'Stock': 150,
 'กลาง': 208,
 'Nano-Cap': 108,
 'ธุรกิจ': 429,
 'ข้อความ': 255,
 'เด่นชัด': 724,
 'สัญญา': 611,
 'บริษัทหลักทรัพย์': 448,
 'ลูกค้า': 580,
 'สถาบัน': 593,
 'ประกาศ': 465,
 'SB': 136,
 'คณะกรรมการ': 261,
 'กำหนด': 234,
 'กนง.': 197,
 'คน': 262,
 'ร้องเพลง': 569,
 'ฟังได้': 514,
 'ไหม': 841,
 'สำนักงาน': 621,
 'พัฒนา': 506,
 'เศรษฐกิจ': 775,
 'สังคม': 610,
 'แห่งชาติ': 803,
 'สภาพัฒน์': 599,
 'กอง': 211,
 'ทุ': 422,
 'นท': 431,
 'ริก': 565,
 'เก': 699,
 'อร': 677,
 '์': 845,
 'Trigger': 162,
 'ตั๋วเงินคลัง': 370,
 'ความหมาย': 279,
 'โดย': 806,
 'สากล': 614,
 'รับ': 555,
 'จดทะเบียน': 309,
 'ติดต่อ': 378,
 'เพื่อน': 755,
 'ครอบครัว': 266,
 'ที่อยู่': 419,
 'ห่างไกล': 667,
 'ทาง': 401,
 'RMF': 130,
 'on': 189,
 'Internet': 81,
 'เสนอขาย': 776,
 'Initial': 79,
 'Public': 127,
 'Offering': 112,
 ':': 14,
 'IPO': 74,
 'Penny': 118,
 'เหรียญ': 780,
 'ออกกำลังกาย': 681,
 'บัญชีเงินสด': 452,
 'หลักประกัน': 658,
 'เต็ม': 727,
 'จำนวน': 323,
 'Balance': 25,
 'LB': 85,
 'สิทธิประโยชน์': 623,
 'ปัจจุบัน': 477,
 'คบ': 264,
 'นานๆ': 434,
 'พาสต้า': 509,
 'REITs': 129,
 'Absolute': 17,
 'Valuation': 164,
 'Equity-Linked': 51,
 'Product': 125,
 'ซื้อขาย': 346,
 'ฟังเพลง': 513,
 'Reinvestment': 134,
 'ติด': 376,
 'ตามเหตุการณ์': 375,
 '9.30': 13,
 '10.00': 6,
 'SET': 137,
 'Connect': 35,
 'หุ้นบุริมสิทธิ': 665,
 'สินค้า': 626,
 'โภคภัณฑ์': 810,
 'TAA': 154,
 'แต่': 786,
 'กลัว': 207,
 'อ้วน': 697,
 'ร้านขายของชำ': 571,
 'โมง': 811,
 'ตั๋วแลกเงิน': 371,
 'ทิศทาง': 411,
 'ตรงข้าม': 357,
 'ส่วนใหญ่': 639,
 'กลยุทธ์': 206,
 'แหล่งที่มา': 801,
 'เงินทุน': 715,
 'โดยทั่วไป': 807,
 'มาจาก': 525,
 'แหล่ง': 800,
 'หนัง': 640,
 'ผลตอบแทน': 485,
 'ความสามารถ': 278,
 'การชำระหนี้': 220,
 'เลือก': 769,
 'หมวด': 650,
 'Sector': 143,
 'บริหาร': 449,
 'เพราะเหตุใด': 750,
 'Portfolio': 121,
 'Rebalancing': 133,
 'พิเศษ': 511,
 'ระบบ': 548,
 'คอมพิวเตอร์': 284,
 'WATCHs': 166,
 'บัญชี': 451,
 'รถติด': 543,
 'จัง': 311,
 'ก่อนกำหนด': 241,
 'Large-cap': 87,
 'ขอ': 244,
 'ชื่อ': 340,
 'ตึง': 380,
 'หน่อย': 647,
 'Issuer': 84,
 'ทุร': 424,
 'รวม': 544,
 'ขาย': 249,
 'คืน': 289,
 'หน่วย': 646,
 'มาร์จิ้น': 527,
 'Margin': 94,
 'Account': 18,
 'งบการเงิน': 301,
 'DW': 42,
 'ระยะเวลา': 549,
 'Term': 158,
 'bitcoin': 182,
 'มั้ย': 523,
 'XB': 169,
 'Mixed': 101,
 'จัดการ': 314,
 'ความขัดแย้ง': 271,
 'ผู้อื่น': 496,
 'หนี้ระยะยาว': 644,
 'Blue-Chip': 27,
 'ใหญ่': 822,
 'แข็งแกร่ง': 784,
 'พูด': 512,
 'ตอบ': 364,
 'ตรง': 356,
 'คำถาม': 286,
 'ทำงาน': 407,
 'ได้เงิน': 828,
 'อ': 671,
 'บ่าง': 458,
 'ไร': 836,
 'Super': 153,
 'AI': 16,
 'Engineer': 48,
 'ปลอดภัย': 473,
 'ขณะ': 242,
 'กลางแจ้ง': 209,
 'เงิน': 712,
 'เท่าๆ': 733,
 'ตามกำหนด': 374,
 'เวลา': 773,
 'สนใจ': 596,
 'ว่า': 592,
 'เท่าไร': 731,
 'Speculative': 149,
 'เก็งกำไร': 703,
 'เตรียมตัว': 725,
 'ตอนนี้': 363,
 'มาก': 524,
 'ความทรงจำ': 274,
 'วัยเด็ก': 588,
 'ชื่นชอบ': 339,
 'เป้าหมาย': 747,
 'การแบ่งประเภท': 232,
 'ดอกไม้': 348,
 'ข้อเสีย': 258,
 'Book': 29,
 'Feeder': 58,
 'ทักษะ': 400,
 'ที่สาธารณะ': 417,
 'นายกรัฐมนตรี': 436,
 'ถัดไป': 390,
 'อายุ': 689,
 'จัดระเบียบ': 317,
 'บ้าน': 461,
 'มีราคา': 534,
 'ต่ำกว่า': 386,
 'มูล': 536,
 'ค่าที่': 298,
 'แท้จริง': 787,
 'คิด': 288,
 'ไหนจะ': 840,
 'ตก': 355,
 'เทรนด์': 728,
 'ในอนาคต': 819,
 'จัดอันดับ': 319,
 'ความน่าเชื่อถือ': 275,
 'หมายถึง': 651,
 'ILB': 73,
 'ขั้นตอน': 248,
 'ท็อป': 425,
 'ปิ้ง': 482,
 'พิซซ่า': 510,
 'ชีส': 338,
 'H': 71,
 'ลักษณะพิเศษ': 577,
 'พันธบัตรรัฐบาล': 508,
 'ร้อน': 570,
 'รัก': 552,
 'Premium': 123,
 'Bond': 28,
 'ไร้': 837,
 'ผู้แทน': 498,
 'ผู้ถือหุ้น': 494,
 'กู้': 238,
 'ทำหน้าที่': 408,
 'ธุรกรรม': 428,
 'ประเทศ': 468,
 'จังหวัด': 313,
 'มีชีวิต': 531,
 'จับคู่': 321,
 'Pairs': 115,
 'Trading': 161,
 'เงื่อนไข': 719,
 'ปรับปรุง': 472,
 'คุณภาพ': 294,
 'นอนหลับ': 432,
 'อาหาร': 690,
 'ค้ำประกัน': 300,
 'จัดสรร': 318,
 'Allocation': 20,
 'ทีละ': 412,
 'รายการ': 560,
 'Gross': 68,
 'Liquidation': 89,
 'ขายทอดตลาด': 251,
 'ไง': 825,
 'สอบ': 609,
 'วันนี้': 586,
 'ฝน': 501,
 'เนี่ย': 735,
 'Floor': 62,
 'เหตุฉุกเฉิน': 778,
 'ทางการเงิน': 403,
 '17.00': 12,
 'หนี้ระยะสั้น': 645,
 'Short-Term': 147,
 'Fixed-Income': 61,
 'YTP': 178,
 'YTC': 176,
 'จุด': 325,
 'ต่าง': 383,
 'บุคคลธรรมดา': 455,
 'ความชุ่มชื้น': 272,
 'ข้อกฎหมาย': 254,
 'XP': 174,
 'ธนาคารแห่งประเทศไทย': 427,
 'กิจการ': 235,
 'เจ้าของ': 720,
 'คนเดียว': 263,
 'หนังสือชี้ชวน': 642,
 'สรุป': 606,
 'Fact': 56,
 'Sheet': 146,
 'ทำให้': 409,
 'ทราบ': 398,
 'ช่วงนี้': 343,
 'อากาศ': 688,
 'Passive': 117,
 'เป็นส่วนใหญ่': 746,
 'ส่วนที่เหลือ': 638,
 'Active': 19,
 'ผลไม้': 486,
 'ประกัน': 464,
 'Guarantee': 70,
 'ปกติ': 463,
 'หาก': 661,
 'การเก็งกำไร': 229,
 'การจัดจำหน่าย': 219,
 'กระทรวงการคลัง': 200,
 'อสังหาฯ': 679,
 'คำสั่ง': 287,
 'เหมาะสม': 779,
 'กรุ๊ป': 204,
 'บี': 453,
 'โสด': 813,
 'SP': 139,
 'สมัคร': 602,
 'เข้า': 705,
 'กล': 205,
 'ต.': 354,
 'ยาก': 540,
 'ปรับ': 471,
 'ช่วง': 342,
 'ทยอย': 396,
 'เงินต้น': 714,
 'Amortizing': 22,
 'Web-based': 168,
 'application': 181,
 'แยกย่อย': 795,
 'ห้างหุ้นส่วนจำกัด': 669,
 'นิติ': 439,
 'บุ': 454,
 'คล': 268,
 'จัดตั้งขึ้น': 316,
 'ตามกฎหมาย': 373,
 'กระทบ': 199,
 'ความต้องการ': 273,
 'ระดับ': 547,
 'สวน': 608,
 'Contrarian': 36,
 'แห่ง': 802,
 'Physical': 120,
 'Normal': 110,
 'เรียกคืน': 763,
 'เงินกู้': 713,
 'ก่อน': 240,
 'Puttable': 128,
 'Coupon': 37,
 'of': 188,
 'Funds': 66,
 'XI': 172,
 'หลักเกณฑ์': 659,
 'เครื่องหมาย': 711,
 'เครียด': 709,
 'เรียน': 764,
 'รู้เรื่อง': 568,
 'ที่ปรึกษา': 415,
 '12.30': 7,
 'บ้า': 459,
 'เวลาว่าง': 774,
 'Financial': 59,
 'Risk': 135,
 'งานอดิเรก': 306,
 'ผู้จัดการ': 491,
 'manager': 187,
 'กำกับ': 233,
 'ส่วนข้อมูล': 637,
 'OTC': 111,
 'คู่': 297,
 'หิว': 662,
 'อะ': 682,
 'ประยุทธ์': 466,
 'นายก': 435,
 'สมมติฐาน': 601,
 'การนำ': 223,
 'สาเหตุ': 618,
 'ระดมทุน': 546,
 'ผลการดำเนินงาน': 484,
 'หลักทรัพย์ค้ำประกัน': 657,
 'Secured': 144,
 'เกี่ยวกับ': 702,
 'ผู้ดูแล': 493,
 'สภาพคล่อง': 598,
 'อัตราส่วน': 686,
 'ทรัพย์สิน': 397,
 'สุทธิ': 630,
 'สิทธิ์': 625,
 'บุริมสิทธิ': 456,
 'สี': 628,
 'per': 190,
 'unit': 194,
 'คุกกี้': 291,
 'Capital': 31,
 'gain': 185,
 'ห้างหุ้นส่วนสามัญ': 670,
 'Par': 116,
 'XD': 170,
 'หน้า': 648,
 'ตั๋ว': 369,
 'ตรา': 359,
 'ไว้': 838,
 'Face': 55,
 'FITCH': 54,
 'Thailand': 159,
 'XE': 171,
 'ทำความสะอาด': 406,
 'พรม': 504,
 'แฝง': 792,
 'ชา': 334,
 'Scripless': 142,
 'ต้นทุน': 388,
 'TB': 155,
 'Preferred': 122,
 'Equity': 50,
 'คุ้มครอง': 296,
 'Protection': 126,
 'อ่านหนังสือ': 696,
 'Micro-cap': 98,
 'นายทะเบียน': 437,
 'ปัญญาประดิษฐ์': 478,
 'เย็น': 760,
 'นี้': 440,
 'ตี๋': 379,
 'น้อย': 443,
 'ป่ะ': 483,
 'ประหยัด': 467,
 'ข้อ': 253,
 'Covenants': 38,
 'สัตว์เลี้ยง': 612,
 'เอกสาร': 783,
 'แนบ': 788,
 'ความผันผวน': 276,
 'ปั๊มน้ำมัน': 480,
 'ใกล้': 814,
 'โครงสร้างพื้นฐาน': 805,
 'Infrastructure': 78,
 'Current': 40,
 'Yield': 179,
 'พยายาม': 502,
 'การออกกำลังกาย': 228,
 'อย่าง': 675,
 'สม่ำเสมอ': 605,
 'คงที่': 260,
 'กระทรวงพาณิชย์': 201,
 'Embedded': 47,
 'Option': 113,
 'สามัญ': 616,
 'Perpetual': 119,
 'เก่ง': 704,
 'ไอศกรีม': 843,
 'เติบโต': 726,
 'Growth': 69,
 'Defensive': 44,
 'ตั้ง': 368,
 'food': 184,
 'waste': 195,
 'เนื้อเพลง': 737,
 'ช่อง': 344,
 'ทางการ': 402,
 'ส่ง': 633,
 'ผู้ซื้อ': 492,
 'เท่าใด': 730,
 'ความเชื่อ': 281,
 'ลอยตัว': 575,
 'ชวน': 331,
 'คุย': 295,
 'ผ่อนคลาย': 500,
 'ไปดู': 832,
 'แมว': 794,
 'ห้อง': 668,
 'เห': 777,
 'นื่่อย': 441,
 'สำนัก': 620,
 'หักบัญชี': 660,
 'ST': 140,
 'จุดเด่น': 326,
 'สิทธิเรียกร้อง': 624,
 'เบียร์': 739,
 'ภาครัฐ': 515,
 'ยูโร': 542,
 'Euro': 52,
 'ต้น': 387,
 'ลำดับ': 578,
 'รับเงิน': 557,
 'เพื่อนร่วมงาน': 756,
 'มีปัญหา': 532,
 'เชิงรุก': 723,
 'รวย': 545,
 'Trustee': 163,
 'เลี้ยง': 768,
 'อิสระ': 692,
 'Discounted': 45,
 'to': 193,
 'เล่น': 771,
 'ค': 259,
 'ริ': 564,
 'ป': 462,
 'โต': 808,
 'ย': 538,
 '\n': 1,
 'อัตโนมัติ': 687,
 'แตกต่าง': 785,
 'อื่นๆ': 694,
 'เปลี่ยนแปลง': 741,
 'งานบริหาร': 305,
 'สาธารณะ': 615,
 'ตัว': 366,
 'มาแรง': 528,
 'เที่ยว': 729,
 'ภูเขา': 519,
 'หรือ': 653,
 'ทะเล': 399,
 'คาด': 285,
 'สูง': 631,
 'Small-cap': 148,
 'เล็ก': 770,
 'YTM': 177,
 'ต่างกัน': 384,
 'Cyclical': 41,
 'วัฏจักร': 583,
 'ระหว่างประเทศ': 551,
 'International': 80,
 'ความเสียหาย': 282,
 'Stop': 151,
 'Loss': 91,
 'NR': 105}

In [ ]:
train_bow

<435x847 sparse matrix of type '<class 'numpy.int64'>'
	with 3626 stored elements in Compressed Sparse Row format>

In [ ]:
# Create Bag-Of-Words (BoW)
train_bow = cvec.transform(X_train['text_token'])

pd.DataFrame(train_bow.toarray(), columns=cvec.get_feature_names_out(),
             index=X_train['text_token'])

,,\n,\r,(,),/,10.00,12.30,14.00,14.30,...,ไร้,ไว้,ไหน,ไหนจะ,ไหม,ไอ,ไอศกรีม,ๆ,์,–
text_token,,,,,,,,,,,,,,,,,,,,,
ทำไม จึง ต้อง ติดตาม ภาวะ การซื้อขาย,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
กระบวนการ ตรวจสอบ การ เปิดบัญชี หลักทรัพย์ มี วิธี ใด บ้าง,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
พันธบัตร ชดเชย เงินเฟ้อ ( Inflation-Linked bond ) คือ อะไร,6,0,0,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Free hold คือ อะไร,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
เบื่อ อ่ะ,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
การซื้อขาย ใน ตลาด TBX กำหนด ราคา ซื้อขาย อย่างไร,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
การ หยุด ความเสียหาย ( Stop Loss ) มี วิธีการ อย่างไร,6,0,0,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ควร เลือก ลงทุน กองทุน ไหน ดี,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
NR หมายถึง อะไร,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
หลักเกณฑ์ ใน การ เปิดบัญชี ซื้อขาย หลักทรัพย์ ทำ อย่างไร,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
# Logistic Regression
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(train_bow, y_train)

LogisticRegression()

In [ ]:
from sklearn.metrics import classification_report

test_bow = cvec.transform(X_test['text_token'])
test_prediction = lr.predict(test_bow)

print(classification_report(test_prediction, y_test))

              precision    recall  f1-score   support

   chat_mode       1.00      1.00      1.00        23
     qa_mode       1.00      1.00      1.00        86

    accuracy                           1.00       109
   macro avg       1.00      1.00      1.00       109
weighted avg       1.00      1.00      1.00       109

### **Try my Question**

In [ ]:
my_question = 'กรณีมีวิกฤตร้ายแรง จะหยุดทำการซื้อขายชั่วคราวต้องมีเงื่อนไขอะไรบ้าง'
mytoken = text_process(my_question)
mytoken

'กรณี มี วิกฤต ร้ายแรง   จะ หยุด ทำ การซื้อขาย ชั่วคราว ต้อง มี เงื่อนไข อะไร บ้าง'

In [ ]:
my_bow = cvec.transform(pd.Series([mytoken]))
my_prediction = lr.predict(my_bow)
my_prediction

array(['qa_mode'], dtype=object)

In [ ]:
my_question = 'ช่วงนี้ไม่อยากไปทำงาน ขอคำแนะนำหน่อย'
mytoken = text_process(my_question)
mytoken

'ช่วงนี้ ไม่ อยาก ไป ทำงาน   ขอ คำแนะนำ หน่อย'

In [ ]:
my_bow = cvec.transform(pd.Series([mytoken]))
my_prediction = lr.predict(my_bow)
my_prediction

array(['chat_mode'], dtype=object)

### **Error Analysis**

In [ ]:
def print_fPred(input = X_test['text_token'], prediction = test_prediction, label = y_test):
  false_pred = pd.DataFrame(columns=['INPUT', 'PREDICTION', 'LABEL'])
  for in_put, predic, la_ble in zip(input, prediction, label):
    if predic != la_ble:
      false_pred = false_pred.append({'INPUT':in_put, 'PREDICTION':predic, 'LABEL':la_ble}, ignore_index = True)
  return false_pred

In [ ]:
print_fPred()

Empty DataFrame
Columns: [INPUT, PREDICTION, LABEL]
Index: []

# Test set

In [ ]:
test_df = pd.read_csv('/content/small_test.csv')
test_df = test_df.iloc[:,1:]

In [ ]:
test_df['text_token'] = test_df['question'].apply(text_process)
test_df

,question,text_token
0,ตลาดหลักทรัพย์ได้กำหนดราคาสูงสุดต่ำสุดของ Warr...,ตลาดหลักทรัพย์ ได้ กำหนด ราคา สูงสุด ต่ำสุด ขอ...
1,ลักษณะแนวทางในการระดมทุนมีอะไรบ้าง,ลักษณะ แนว ทางใน การ ระดมทุน มี อะไร บ้าง
2,Gross Price หรือ Dirty Price มีวิธีการจ่ายดอกเ...,Gross Price หรือ Dirty Price มี วิธี...
3,รายได้จากการลงทุนต่อ (Reinvestment income) คือ...,รายได้ จาก การลงทุน ต่อ ( Reinvestment inc...
4,ตัวอย่างลำดับเหตุการณ์ที่เกี่ยวข้องกับการจ่ายเ...,ตัวอย่าง ลำดับ เหตุการณ์ ที่ เกี่ยวข้อง กับ กา...
5,กรณีมีวิกฤตร้ายแรง จะหยุดทำการซื้อขายชั่วคราวต...,กรณี มี วิกฤต ร้ายแรง จะ หยุด ทำ การซื้อขาย ...
6,เงินปันผลกรณีนิติบุคคลทั่วไป มีกรณีใดบ้าง,เงินปันผล กรณี นิติบุคคล ทั่วไป มี กรณี ใด บ้าง
7,การวิเคราะห์ SWOT ต้องพิจารณาปัจจัยอะไรบ้าง,การ วิเคราะห์ SWOT ต้อง พิจารณา ปัจจัย อะไ...
8,กรณีระบบซื้อขายของตลาดฯ ขัดข้อง จะหยุดทำการซื้...,กรณี ระบบ ซื้อขาย ของตลาด ฯ ขัดข้อง จะ หยุ...
9,การเสียภาษีบุคคลธรรมดาได้รับการยกเว้นอะไรบ้าง,การ เสียภาษี บุคคลธรรมดา ได้รับ การยกเว้น อะไร...
10,ดอกเบี้ยรับ (Interest payment) คืออะไร,ดอกเบี้ย รับ ( Interest payment ) คือ อะไร
11,ช่วงราคาซื้อขาย (Spread/Trick sizes) คืออะไร,ช่วง ราคา ซื้อขาย ( Spread / Trick sizes )...
12,อัตราภาษีของผู้ลงทุนชาวไทยที่เป็นนิติบุคคล คือ...,อัตราภาษี ของ ผู้ลงทุน ชาวไทย ที่ เป็น นิติบุค...
13,การเสียภาษีของนิติบุคคลที่จดทะเบียนในตลาดหลักท...,การ เสียภาษี ของ นิติบุคคล ที่ จดทะเบียน ใน ตล...
14,กำไรจากส่วนต่างราคา มาจากไหน,กำไร จาก ส่วน ต่าง ราคา มาจาก ไหน
15,ส่วนลดของตราสารหนี้ มาจากไหน,ส่วนลด ของ ตราสาร หนี้ มาจาก ไหน
16,รายงานประจำปี (Annual Report) คืออะไร,รายงานประจำปี ( Annual Report ) คือ อะไร
17,ทางเลือกเงินปันผลสำหรับบุคคลธรรมดา มีอะไรบ้าง,ทางเลือก เงินปันผล สำหรับ บุคคลธรรมดา มี อะไ...
18,ระบบสำรองของตลาดหลักทรัพย์ คืออะไร,ระบบ สำรอง ของ ตลาดหลักทรัพย์ คือ อะไร
19,ผลตอบแทนของตราสารทุนมีอะไรบ้าง,ผลตอบแทน ของ ตราสาร ทุน มี อะไร บ้าง
20,การเสียภาษีของนิติบุคคลทั่วไป มีอะไรบ้าง,การ เสียภาษี ของ นิติบุคคล ทั่วไป มี อะไร บ้าง
21,การเสียภาษีเงินปันผลบุคคลธรรมดา คิดอย่างไร,การ เสียภาษี เงินปันผล บุคคลธรรมดา คิด อย่างไร
22,ราคาของตราสารหนี้มีกี่ประเภท,ราคา ของ ตราสาร หนี้ มี กี่ ประเภท
23,Relative Valuation คืออะไร,Relative Valuation คือ อะไร
24,Absolute Valuation คืออะไร,Absolute Valuation คือ อะไร
25,หนังสือชี้ชวนส่วนสรุปสำคัญ (Fund Fact Sheet) ค...,หนังสือชี้ชวน ส่วน สรุป สำคัญ ( Fund Fact ...
26,ภาพรวมของผลตอบแทนและความเสี่ยงของกองทุนรวม คือ...,ภาพรวม ของ ผลตอบแทน และ ความเสี่ยง ของ กองทุนร...
27,เพราะเหตุใดความเสี่ยงจากการลงทุนผ่านกองทุนรวมอ...,เพราะเหตุใด ความเสี่ยง จาก การลงทุน ผ่าน กองทุ...
28,เครื่องมือของนโยบายการเงินมีอะไรบ้าง,เครื่องมือ ของ นโยบาย การเงิน มี อะไร บ้าง
29,อัตราภาษีของผู้ลงทุนชาวต่างชาติที่เป็นบุคคลธรร...,อัตราภาษี ของ ผู้ลงทุน ชาวต่างชาติ ที่ เป็น บุ...
30,กำไรจากส่วนต่างราคา (Capital gain) คืออะไร,กำไร จาก ส่วน ต่าง ราคา ( Capital gain ) ...
31,วัฏจักรเศรษฐกิจประกอบด้วยอะไรบ้าง,วัฏจักร เศรษฐกิจ ประกอบด้วย อะไร บ้าง
32,การเสียภาษีกำไรจากส่วนต่างราคาของนิติบุคคลทั่ว...,การ เสียภาษี กำไร จาก ส่วน ต่าง ราคา ของ นิติบ...
33,การประเมินมูลค่าหุ้นสามัญมีกี่รูปแบบ,การประเมิน มูลค่า หุ้นสามัญ มี กี่ รูปแบบ
34,เงินปันผลกรณีนิติบุคคลที่จดทะเบียนในตลาดหลักทร...,เงินปันผล กรณี นิติบุคคล ที่ จดทะเบียน ใน ตลาด...
35,อัตราภาษีของผู้ลงทุนชาวต่างชาติที่เป็นนิติบุคค...,อัตราภาษี ของ ผู้ลงทุน ชาวต่างชาติ ที่ เป็น นิ...
36,ดอกเบี้ยรับ มาจากไหน,ดอกเบี้ย รับ มาจาก ไหน
37,ข้อเสียของ Gross Price คืออะไร,ข้อเสีย ของ Gross Price คือ อะไร
38,การเสียภาษีกำไรจากส่วนต่างราคาของนิติบุคคลที่จ...,การ เสียภาษี กำไร จาก ส่วน ต่าง ราคา ของ นิติบ...
39,การเสียภาษีเงินปันผลนิติบุคคลทั่วไป คิดอย่างไร,การ เสียภาษี เงินปันผล นิติบุคคล ทั่วไป คิด ...
40,วิธีการประกาศหยุดการซื้อขายของตลาดหลักทรัพย์ ค...,วิธีการ ประกาศ หยุด การซื้อขาย ของ ตลาดหลักทรั...
41,กรณีระบบซื้อขายของสมาชิก (บล.) ขัดข้อง จะหยุดท...,กรณี ระบบ ซื้อ ขายของ สมาชิก ( บล. ) ขัดข้...
42,ตลาดผูกขาดแท้จริงคืออะไร,ตลาด ผูกขาด แท้จริง คือ อะไร
43,ดุลบัญชีเดินสะพัดประกอบด้วยอะไรบ้าง,ดุล บัญชีเดินสะพัด ประกอบด้วย อะไร บ้าง
44,TSR มีลักษณะอย่างไร,TSR มี ลักษณะ อย่างไร
45,ตลาดหลักทรัพย์ได้กำหนดราคาสูงสุดต่ำสุดของหุ้นส...,ตลาดหลักทรัพย์ ได้ กำหนด ราคา สูงสุด ต่ำสุด ขอ...
46,ค่าสัมประสิทธิ์สหสัมพันธ์คืออะไร,ค่าสัมประสิทธิ์ สห สัมพันธ์ คือ อะไร
47,ผลตอบแทนจากการปันผล (Dividend) คืออะไร,ผลตอบแทน จาก การ ปันผล ( Dividend ) คือ อะไร
48,ตลาดหลักทรัพย์ได้กำหนดราคาสูงสุดต่ำสุดของหุ้นส...,ตลาดหลักทรัพย์ ได้ กำหนด ราคา สูงสุด ต่ำสุด ขอ...
49,ตราสารทุน คืออะไร,ตราสาร ทุน คือ อะไร

In [ ]:
x = test_df['text_token']

In [ ]:
test_df['label'] = 'qa_mode'
y = test_df['label']

In [ ]:
my_bow = cvec.transform(pd.Series(x))
my_prediction = lr.predict(my_bow)

In [ ]:
my_prediction

array(['qa_mode', 'qa_mode', 'qa_mode', 'qa_mode', 'chat_mode', 'qa_mode',
       'qa_mode', 'qa_mode', 'qa_mode', 'qa_mode', 'qa_mode', 'qa_mode',
       'qa_mode', 'qa_mode', 'qa_mode', 'qa_mode', 'qa_mode', 'qa_mode',
       'qa_mode', 'qa_mode', 'qa_mode', 'qa_mode', 'qa_mode', 'qa_mode',
       'qa_mode', 'qa_mode', 'qa_mode', 'qa_mode', 'qa_mode', 'qa_mode',
       'qa_mode', 'qa_mode', 'qa_mode', 'qa_mode', 'qa_mode', 'qa_mode',
       'qa_mode', 'qa_mode', 'qa_mode', 'qa_mode', 'qa_mode', 'qa_mode',
       'qa_mode', 'qa_mode', 'qa_mode', 'qa_mode', 'qa_mode', 'qa_mode',
       'qa_mode', 'qa_mode'], dtype=object)

In [ ]:
print(classification_report(my_prediction, y))

              precision    recall  f1-score   support

   chat_mode       0.00      0.00      0.00         1
     qa_mode       0.98      1.00      0.99        49

    accuracy                           0.98        50
   macro avg       0.49      0.50      0.49        50
weighted avg       0.96      0.98      0.97        50

/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))